server.port=8080
spring.cloud.gateway.discovery.locator.enabled=true

spring.cloud.gateway.routes[0].id=shopping_cart_service_route
spring.cloud.gateway.routes[0].uri=lb://SHOPPING-CART
spring.cloud.gateway.routes[0].predicates[0]=Path=/shopping-cart/**
spring.cloud.gateway.routes[0].filters[0]=PrefixPath=/api/v1

spring.cloud.gateway.routes[1].id=shopping_store_service_route
spring.cloud.gateway.routes[1].uri=lb://SHOPPING-STORE
spring.cloud.gateway.routes[1].predicates[0]=Path=/shopping-store/**
spring.cloud.gateway.routes[1].filters[0]=PrefixPath=/api/v1
spring.cloud.gateway.routes[1].filters[1].name=Retry
spring.cloud.gateway.routes[1].filters[1].args.retries=3
spring.cloud.gateway.routes[1].filters[1].args.statuses=NOT_FOUND

spring.cloud.gateway.routes[2].id=warehouse_service_route
spring.cloud.gateway.routes[2].uri=lb://WAREHOUSE
spring.cloud.gateway.routes[2].predicates[0]=Path=/warehouse/**
spring.cloud.gateway.routes[2].filters[0]=PrefixPath=/api/v1