spring.application.name=shopping-cart
server.port=0

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:6541/shopping_cart_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true

logging.level.ru.yandex.practicum=DEBUG
logging.level.org.springframework=ERROR

resilience4j.circuitbreaker.instances.warehouse.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.warehouse.sliding-window-size=10
resilience4j.circuitbreaker.instances.warehouse.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.warehouse.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.warehouse.wait-duration-in-open-state=20s
resilience4j.circuitbreaker.instances.warehouse.permitted-number-of-calls-in-half-open-state=3