spring.application.name=collector

spring.kafka.producer.topic.sensors=telemetry.sensors.v1
spring.kafka.producer.topic.hubs=telemetry.hubs.v1

spring.kafka.bootstrap-servers=localhost:9092

logging.level.ru.yandex.practicum.kafka=INFO
logging.level.org.springframework=ERROR
logging.level.org.apache.kafka=WARN

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true