spring.application.name=aggregator

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=aggregator-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false

spring.kafka.producer.topic.sensors=telemetry.sensors.v1
spring.kafka.producer.topic.snapshots=telemetry.snapshots.v1

logging.level.ru.yandex.practicum=INFO
logging.level.org.apache.kafka=WARN
logging.level.org.springframework=ERROR